[build]
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api/:splat"
    status = 200

[[redirects]]
    from = "/linkvertise"
    to = "https://www.linkvertise.com"
    status = 200
    force = true