[build]
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api/:splat"
    status = 200

    from = "/linkvertise/*"
    to = "https://linkvertise.com/75631/RGBInvGUI/1"
    status = 200