[build]
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api/:splat"
    status = 200

[[redirects]]
    from = "/linkvertise/*"
    to = "https://link-to.net/551092/:splat"
    status = 200
    force = true